apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tempo.querierFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
  {{- with .Values.querier.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  minReadySeconds: 10
  replicas: {{ .Values.queryFrontend.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "tempo.querierLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        {{- include "tempo.querierLabels" . | nindent 8 }}
        {{- include "tempo.gossipRing.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - -target=querier
        - -config.file=/conf/tempo.yaml
        - -mem-ballast-size-mbs=1024
        image: {{ include "tempo.querierImage" . }}
        imagePullPolicy: {{ .Values.tempo.image.pullPolicy }}
        name: querier
        ports:
        - containerPort: 7946
          name: http-memberlist
          protocol: TCP
        - containerPort: 3100
          name: prom-metrics
        resources:
        {{- toYaml .Values.querier.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /conf
          name: tempo-conf
      {{- with .Values.querier.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.querier.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.querier.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - configMap:
          name: {{ template "tempo.fullname" . }}
        name: tempo-conf
