# Test values to limit the load during CI
alertmanager:
  persistentVolume:
    enabled: false

compactor:
  persistentVolume:
    enabled: false

config:
  alertmanager:
    storage:
      type: "local"
      local:
        path: "/data/configs"

  blocks_storage:
    backend: "filesystem"
    tsdb:
      dir: "/data/tsdb"
    bucket_store:
      sync_dir: "/data/tsdb-sync"
    filesystem:
      dir: "/data/store"

  ruler:
    storage:
      type: "local"
      local:
        directory: "/data/rules"

# Even though the admin-api requires an object store, it can be omitted because the admin-api
# doesn't need to perform any actions against the store in the CI test.
minio:
  enabled: false

ingester:
  persistentVolume:
    enabled: false

store_gateway:
  persistentVolume:
    enabled: false
