apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "tempo.queryFrontendFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
  {{- with .Values.queryFrontend.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  minReadySeconds: 10
  replicas: {{ .Values.queryFrontend.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "tempo.queryFrontendLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        {{- include "tempo.queryFrontendLabels" . | nindent 8 }}
        {{- include "tempo.gossipRing.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - -target=query-frontend
        - -config.file=/conf/tempo.yaml
        - -mem-ballast-size-mbs=1024
        image: {{ include "tempo.queryFrontendImage" . }}
        imagePullPolicy: {{ .Values.tempo.image.pullPolicy }}
        name: query-frontend
        ports:
        - containerPort: 3100
          name: prom-metrics
        - containerPort: 9095
          name: grpc-metrics
        resources:
        {{- toYaml .Values.queryFrontend.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /conf
          name: tempo-conf
      - args:
        - --query.base-path=/
        - --grpc-storage-plugin.configuration-file=/conf/tempo-query.yaml
        - --query.bearer-token-propagation=true
        image: {{ include "tempo.queryImage" . }}
        imagePullPolicy: {{ .Values.tempo.image.pullPolicy }}
        name: tempo-query
        ports:
        - containerPort: 16686
          name: jaeger-ui
        - containerPort: 16687
          name: jaeger-metrics
        env:
        - name: JAEGER_AGENT_HOST
          value: {{ template "tempo.fullname" . }}
        resources:
            {{- toYaml .Values.queryFrontend.query.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /conf
          name: tempo-conf
      {{- with .Values.queryFrontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queryFrontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.queryFrontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - configMap:
          name: {{ template "tempo.fullname" . }}
        name: tempo-conf
