{{- if not .Values.license.external }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.license.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.license.secretName }}
    chart: {{ template "metrics_enterprise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  license.jwt: {{ .Values.license.contents | b64enc }}
{{- end }}
