{{- if not .Values.useExternalConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "metrics_enterprise.fullname" . }}
  labels:
    app: {{ template "metrics_enterprise.name" . }}
    chart: {{ template "metrics_enterprise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  enterprise-metrics.yaml: {{ tpl (toYaml .Values.config) . | b64enc}}
{{- end }}
