{{- if not .Values.useExternalLicense }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "metrics_enterprise.fullname" . }}-license
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "metrics_enterprise.name" . }}-license
    chart: {{ template "metrics_enterprise.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  license.jwt: {{ .Values.license.contents | b64enc }}
{{- end }}
