apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "tempo.ingesterFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.ingesterLabels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.ingester.replicas }}
  selector:
    matchLabels:
      {{- include "tempo.ingesterSelectorLabels" . | nindent 6}}
  serviceName: ingester
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "tempo.ingesterLabels" . | nindent 8 }}
        {{- include "tempo.gossipRing.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - -target=ingester
        - -config.file=/conf/tempo.yaml
        - -mem-ballast-size-mbs=1024
        image: {{ include "tempo.ingesterImage" . }}
        imagePullPolicy: {{ .Values.tempo.image.pullPolicy }}
        name: ingester
        ports:
        - name: grpc
          containerPort: 9095
        - name: http-memberlist
          containerPort: 7946
        - name: http
          containerPort: 3100
        readinessProbe:
          {{- toYaml .Values.tempo.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.ingester.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /conf
          name: tempo-conf
        - mountPath: /var/tempo
          name: data
      {{- with .Values.ingester.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingester.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ingester.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - configMap:
          name: {{ template "tempo.fullname" . }}
        name: tempo-conf
  {{- if not .Values.ingester.persistence.enabled }}
      - name: data
        emptyDir: {}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- with .Values.tempo.ingester.persistence.storageClass }}
        storageClassName: {{ if (eq "-" .) }}""{{ else }}{{ . }}{{ end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.tempo.ingester.persistence.size | quote }}
  {{- end }}
